import React from "react";
import {
  AlertTriangle,
  Trash2,
  X,
  FileSpreadsheet,
  BrainCircuit,
  Activity,
  Briefcase,
  Loader2,
  CheckCircle2,
  ShieldAlert,
} from "lucide-react";
import "./DeleteConfirmModal.css";

const DeleteConfirmModal = ({
  isOpen,
  dataset,
  isDeleting,
  deleteResult,
  onConfirm,
  onClose,
}) => {
  if (!isOpen) return null;

  const hasResult = deleteResult !== null;

  return (
    <div className="modal-overlay" role="presentation" onClick={!isDeleting ? onClose : undefined}>
      <div
        className="modal-container glass-panel modal-enter"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Close button */}
        {!isDeleting && (
          <button type="button" className="modal-close-btn clickable" onClick={onClose}>
            <X size={18} />
          </button>
        )}

        {/* Deleting in progress */}
        {isDeleting && (
          <div className="modal-body modal-state-deleting">
            <div className="modal-icon-ring deleting-ring">
              <Loader2 size={36} className="animate-spin" />
            </div>
            <h3>Cleaning Up Resources…</h3>
            <p className="modal-subtitle">
              Removing dataset, trained models, predictions, and jobs
            </p>
            <div className="deleting-progress-bar">
              <div className="deleting-progress-fill" />
            </div>
          </div>
        )}

        {/* Success result */}
        {!isDeleting && hasResult && (
          <div className="modal-body modal-state-success">
            <div className="modal-icon-ring success-ring">
              <CheckCircle2 size={36} />
            </div>
            <h3>Cascade Delete Complete</h3>
            <p className="modal-subtitle">
              All related resources have been permanently removed
            </p>

            <div className="result-summary-grid">
              <div className="result-card">
                <FileSpreadsheet size={20} className="result-icon dataset-icon" />
                <span className="result-label">Dataset</span>
                <span className="result-value">Deleted</span>
              </div>
              <div className="result-card">
                <BrainCircuit size={20} className="result-icon model-icon" />
                <span className="result-label">Models Removed</span>
                <span className="result-value result-count">
                  {deleteResult?.deleted_models ?? 0}
                </span>
              </div>
              <div className="result-card">
                <Activity size={20} className="result-icon prediction-icon" />
                <span className="result-label">Predictions</span>
                <span className="result-value">Cleared</span>
              </div>
              <div className="result-card">
                <Briefcase size={20} className="result-icon job-icon" />
                <span className="result-label">Jobs</span>
                <span className="result-value">Cleared</span>
              </div>
            </div>

            <button type="button" className="modal-btn btn-done clickable" onClick={onClose}>
              Close
            </button>
          </div>
        )}

        {/* Confirmation prompt */}
        {!isDeleting && !hasResult && (
          <div className="modal-body modal-state-confirm">
            <div className="modal-icon-ring danger-ring">
              <ShieldAlert size={36} />
            </div>
            <h3>Delete Dataset?</h3>
            <p className="modal-subtitle">
              This action is <strong>permanent</strong> and cannot be undone
            </p>

            <div className="dataset-info-badge">
              <FileSpreadsheet size={16} />
              <span className="badge-name" title={dataset?.filename}>
                {dataset?.filename}
              </span>
            </div>

            <div className="cascade-warning">
              <AlertTriangle size={16} className="warning-icon" />
              <div className="warning-text">
                <strong>Cascade deletion</strong>, the following related
                resources will also be permanently removed:
              </div>
            </div>

            <ul className="cascade-list">
              <li>
                <BrainCircuit size={14} />
                <span>All trained ML models</span>
              </li>
              <li>
                <Activity size={14} />
                <span>All predictions generated by those models</span>
              </li>
              <li>
                <Briefcase size={14} />
                <span>All associated training jobs</span>
              </li>
            </ul>

            <div className="modal-actions">
              <button type="button"
                className="modal-btn btn-cancel clickable"
                onClick={onClose}
              >
                Cancel
              </button>
              <button type="button"
                className="modal-btn btn-danger clickable"
                onClick={onConfirm}
              >
                <Trash2 size={16} />
                Delete Everything
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default DeleteConfirmModal;
